#./django-docker/docker-compose.yml
version: '3.10.6'

services:
  web:
    build:
         context: ./app 
         dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/app/
    ports:
      - 4000:8000
    env_file:
      - ./env/django.env
  node_css_packages:
    image: "node:lts"
    volumes:
      - ./app/:/usr/app/
    working_dir: /usr/app/        
    command: >
      bash -c "npm install && npm run sass"

    tty: true
      

